---
title: "Bio-Sparte"
output: html_notebook
---

library aufrufen das wir nutzen wollen

```{r setup}
library(tidyverse)

```

Datanbankverbindung aufbauen

```{r}
DB_HOST='86.119.36.94' #or 86.119.36.94 or server2053.cs.technik.fhnw.ch
DB_PORT = 5432
DB_DBNAME = 'warenkorb_db' # or 'warenkorb_db'
DB_USERNAME = 'db_user' 
DB_PASSWORD = 'db_user_pw'

con <- DBI::dbConnect(odbc::odbc(),
                      Driver   = "PostgreSQL Unicode(x64)",
                      Server   = DB_HOST,
                      Database = DB_DBNAME,
                      UID      = DB_USERNAME,
                      PWD      = DB_PASSWORD,
                      Port     = DB_PORT)
```

Definition von tabellen auf variabeln in R um damit umzugehen

```{r}
t_products <- tbl(con, "product")
t_aisles <- tbl(con, "aisle")
t_departments <- tbl(con, "department")
t_orders <- tbl(con, "orders")
t_orders_prior <- tbl(con, "orders_product_prior")
t_orders_train <- tbl(con, "orders_product_train")
```
Wir wollen die Anzahl and organische produkte und nicht organische produkte erhalten und aufzeigen

```{r}
t_organic_products <- t_products %>% 
  select(product_name) %>%
  filter(str_detect(tolower(product_name), pattern = "organic"))

t_notorganic_products <- t_products %>% 
  select(product_name) %>%
  filter(!str_detect(tolower(product_name), pattern = "organic"))

organic_count <- tally(t_organic_products)
notorganic_count <- tally(t_notorganic_products)
```

Jetzt wollen wir graphisch das verhältnis von Bio zu nicht Bio aufzeichnen

```{r}
#ggplot(organic_count, notorganic_count ,mapping = aes(aes(y = tally(t_products)))) +
#  geom_bar()
organic_count
```

Changes Mario und Riccard:

```{r}
t_products %>%
  mutate(organic = str_detect(tolower(product_name), pattern = "organic")) %>%
  group_by(organic) %>%
  count() %>%
  mutate(n = as.integer(n)) %>%
  ggplot() +
    geom_col(aes(x=organic,y=n))
```












