---
title: "DataCleansing"
output: html_notebook
---
```{r setup}
#install.packages("RPostgreSQL")
#install.packages("tidyverse")

library(DBI)
library(tidyverse)
require("RPostgreSQL")
```
#Datanbankverbindung aufbauen
```{r}
source('DbConnection.R')
```
#Data Cleansing nach Quelle : https://towardsdatascience.com/data-cleaning-with-r-and-the-tidyverse-detecting-missing-values-ea23c519bc62
```{r}
#Alle Produkte
t_products <- as.data.frame(t_products)
#glimpse(t_products)

#Alle Gänge
t_aisles <- as.data.frame(t_aisles)
#glimpse(t_aisles)

#Alle Abteilungen
t_departments <- as.data.frame(t_departments)
#glimpse(t_departments)

#Alle Bestellungen
t_orders <- as.data.frame(t_orders)
#glimpse(t_orders)

#t_orders_product <- as.data.frame(t_orders_product)
#glimpse(t_orders_prior)
```
#Untersuchung der NA Werte
```{r}
sum(is.na(t_products)) #0
sum(is.na(t_aisles)) #0
sum(is.na(t_departments))# ?
sum(is.na(t_orders))#c.a 200`000
#sum(is.na(t_orders_products)) #0
#sum(is.na(t_orders_train)) #0
```
#Zusammenfassung der NA Werte
```{r}
#Alle NA Werte sind

sum(is.na(t_orders$days_since_prior_order))

t_orders %>% 
  group_by(days_since_prior_order) %>% 
  summarise(non_na_count = sum(is.na(days_since_prior_order)))
```
#(Überschreibung der NA Werte in t_orders) wird nicht gemacht!
```{r}
#Für was für einen Wert soll ich NA ersetzten, o gibt es schon. NA sollten aussortiert werden

# esetzen der NA  Werte mit 0
#t_orders <- t_orders %>%
#  mutate(days_since_prior_order = replace(days_since_prior_order, is.na(days_since_prior_order), 0))

#t_orders

#sum(is.na(t_orders$days_since_prior_order))

```
#Unterteilung in Ersteinkauf und Cleanen Datensatz
```{r}
#Erstellung des Dataframes : t_orders_Clean
#t_orders_Clean <- t_orders %>% drop_na()
#t_orders_Clean
#sum(is.na(t_orders_Clean))  # 0 NA Werte

#Erstellung des Dataframes : t_orders_FirstBuy
#t_orders_FirstBuy <- t_orders %>%
 # filter(is.na(days_since_prior_order)) %>%
  #select(-c(days_since_prior_order))
  
t_orders_FirstBuy
```
#Aisles werte:missing und other aussortieren
```{r}
t_departments

#t_aisles_Clean <- t_aisles %>%
 # filter(!str_detect(tolower(aisle), pattern = "missing"), !str_detect(tolower(aisle), pattern = "other"))

#t_aisles_Missing <- t_aisles %>%
 #   filter(aisle == "missing")

#t_aisles_Other <- t_aisles %>%
 #   filter(aisle == "other")

t_aisles_Clean  
t_aisles_Missing
t_aisles_Other
```
#Deparetments werte:missing und other aussortieren
```{r}
#t_departments_Clean <- t_departments %>%
 # filter(department != "missing" | department != "other")

#t_departments_Missing <- t_departments %>%
 #   filter(department == "missing")

#t_departments_Other <- t_departments %>%
 #   filter(department == "other")

t_departments_Clean  
t_departments_Missing
t_departments_Other
```